language: php

php:
  - 7.1
  - 7.2
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
